# Site settings
title: TODAY I LEARNED
tagline: by Petr Stepchenko
email: gayanvirajith@gmail.com
description: > # TODO: ADD DESCRIPTION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nitrino.io/til/" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Petr Stepchenko"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!

variables:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social:
    github: nitrino
    twitter: pstepchenko
    facebook: pstepchanko
    telegram: nitrodev

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  disqus_shortname: nitrino-io

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key:
  google_webmaster_key:
  yandex_metrica: 46357395

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed

plugins: [jekyll-paginate]
